### ISSUE TITLE
Cannot download the SO dump

### ISSUE THREAD

**Issue by Moshiii** [muldon/CROKAGE-replication-package#1]
Hi,
Thanks for the excellent work!

I am a researcher and I am trying to reproduce your work.
When I click the link for downloading the source code and SO dump:

![image](https://user-images.githubusercontent.com/7553188/103324843-0136bd80-4a17-11eb-9f88-7d7c7737be93.png)
![image](https://user-images.githubusercontent.com/7553188/103324859-0c89e900-4a17-11eb-917f-deee857939b5.png)

but I got blocked (I guess):
![image](https://user-images.githubusercontent.com/7553188/103324765-dcdae100-4a16-11eb-961d-7dd4abbc1c02.png)

Please investigate and fix.

Thanks!

**Comment by papb** [comment]
Same issue here.

**Comment by masud-technope** [comment]
@muldon please take a look, probably the server is down!

**Comment by muldon** [comment]
The firewall of the university is blocking the access to the file. We are trying to contact them. As soon as we have it fixed I let you know.

**Comment by muldon** [comment]
the service has been restored
